### ISSUE TITLE
Proposed Marketing Committee meeting agenda for January-10-22

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/community#107]
## Meeting Details

- **Date/Time:** January 10, 2022 @ 12:00pm PST / 8:00pm GMT
- **Location:** Discord Voice Channel #Meeting-Room
- **Moderator:** TBD
- **Note Taker**: TBD

## SIG Updates

Marketing Committee [Dashboard](https://github.com/o3de/community/blob/main/committee/committee-marketing/readme.md) added to repo.

## Meeting Agenda

Marketing needs for 1/27 point release (21.11.2):
- Blog posts
- Site updates

o3de.org:
- Site support needs (Server-based search, analytics)
- Content performance tracking/reporting

Additional topics proposed below...

## Outcomes from Discussion topics

TBD

## Action Items

TBD

## Open Discussion Items

TBD

**Comment by forhalle** [comment]
I would like to discuss the release management process, and present [this GHI issue](https://github.com/o3de/o3de/issues/6755) which will be used to track the Marketing-related work.

**Comment by inkcatcopy** [comment]
We would also like to discuss the following:

###  Addressing social media complaints - 
_Many users are bringing up two major problems:_
1. The fact the so-called "stable build" is not actually a _stable build._
2. That bugs are being brought up (especially on the Discord) but O3DE isn't finding ways to discuss this or highlight this. The non-acknowledgement isn't helping the situation. It's frustrating and disheartening both current users and potential users alike.  We need a way to turn these _**lemons**_ into **_lemonade_** by finding a constructive way to address these and make this part of a highlighted, collaborative effort as an open source engine.

### Language clarity and expansiveness in responding to user questions -
_Primarily a Discord observation:_
- We've observed that, if O3DE cannot currently perform some asked-about function, some leadership/moderator level folks on the Discord are simply answering with, "No." This is a complete sentence that shuts down any further discussion. Great for boundary setting; bad for engaging in open discourse, let alone user retention. _"Can O3DE do XYZ yet?"_ shouldn't be given just a flat _no_ but some sort of expansion answer such as, _"No, not yet. But, this is a feature we are working on/will be launched in the future/we are working on an integration for."_
- -At ICC, we like to refer to this as soup example. _"Would you like soup?"_ can be answered as "no" because

> 1. No, I already ate.
> 2. No, because my hands are full.
> 3. No, but I will later.
> 4. No, I don't like this soup.

**Comment by lmbr-pip** [comment]
Meeting occurred, closing as stale issue
